spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reg
    username: root
    password: root
  jpa:
    show-sql: true
    
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone:
        http://localhost:8761/eureka